function analysisResults = main_active(cfg)
%MAIN_ACTIVE Run the preregistered TrafoDNA V3 active-response study.
%   RESULTS = MAIN_ACTIVE() uses DEFAULTACTIVECONFIG. V2.2 remains intact.

projectRoot = fileparts(mfilename('fullpath'));
addpath(genpath(projectRoot));
if nargin < 1 || isempty(cfg)
    cfg = defaultActiveConfig();
end
localEnsureDirectories(cfg);
rng(cfg.rngSeed,'twister');

if cfg.runtime.verbose
    fprintf(['Starting TrafoDNA V3 active study: %d cores, %d scenarios, ' ...
        '%d sweeps, %d challenges.\n'],cfg.dataset.numCores, ...
        cfg.dataset.numConditions,cfg.dataset.repetitions, ...
        numel(cfg.active.challenges));
end

cores = repmat(createActiveCore(1,cfg),cfg.dataset.numCores,1);
for coreId = 1:cfg.dataset.numCores
    cores(coreId) = createActiveCore(coreId,cfg);
end
dataset = generateActiveDataset(cores,cfg);
splits = splitDataset(dataset.metadata,cfg);

identityModel = tuneIdentityModel(dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train),dataset.metadata(splits.train,:), ...
    dataset.features(splits.validation,:), ...
    dataset.metadata.CoreId(splits.validation), ...
    dataset.metadata(splits.validation,:),cfg);
[validationPrediction,validationMetrics] = localIdentityEvaluation( ...
    identityModel,dataset.features(splits.validation,:), ...
    dataset.metadata(splits.validation,:));
[testPrediction,testMetrics] = localIdentityEvaluation(identityModel, ...
    dataset.features(splits.test,:),dataset.metadata(splits.test,:));
[developmentPrediction,developmentMetrics] = localIdentityEvaluation( ...
    identityModel,dataset.features(splits.unseen,:), ...
    dataset.metadata(splits.unseen,:));
[finalPrediction,finalMetrics] = localIdentityEvaluation(identityModel, ...
    dataset.features(splits.finalHoldout,:), ...
    dataset.metadata(splits.finalHoldout,:));

pufIdentityModel = trainActivePUFTransform( ...
    dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train), ...
    dataset.metadata(splits.train,:),cfg);
pufModel = generateBinaryFingerprint(dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train),cfg,pufIdentityModel, ...
    dataset.metadata(splits.train,:),dataset.features(splits.validation,:), ...
    dataset.metadata.CoreId(splits.validation), ...
    dataset.metadata(splits.validation,:));
pooledMask = splits.test | splits.unseen;
pufMetrics = evaluatePUF(pufModel,dataset.features(pooledMask,:), ...
    dataset.metadata.CoreId(pooledMask),dataset.metadata(pooledMask,:));
finalPUFMetrics = evaluatePUF(pufModel,dataset.features(splits.finalHoldout,:), ...
    dataset.metadata.CoreId(splits.finalHoldout), ...
    dataset.metadata(splits.finalHoldout,:));
[worstFinalPUFReliability,finalPUFByCondition] = ...
    computeWorstConditionPUFReliability(pufModel, ...
    dataset.features(splits.finalHoldout,:), ...
    dataset.metadata.CoreId(splits.finalHoldout), ...
    dataset.metadata(splits.finalHoldout,:));

readsPerDecision = cfg.session.readsPerDecision;
[~,developmentSessionIdentity] = evaluateIdentitySessions(identityModel, ...
    dataset.features(splits.unseen,:),dataset.metadata(splits.unseen,:), ...
    readsPerDecision);
[developmentSessionPUF,~] = evaluatePUFSessions(pufModel, ...
    dataset.features(splits.unseen,:),dataset.metadata(splits.unseen,:), ...
    readsPerDecision);
[~,finalSessionIdentity] = evaluateIdentitySessions(identityModel, ...
    dataset.features(splits.finalHoldout,:), ...
    dataset.metadata(splits.finalHoldout,:),readsPerDecision);
[finalSessionPUF,~] = evaluatePUFSessions(pufModel, ...
    dataset.features(splits.finalHoldout,:), ...
    dataset.metadata(splits.finalHoldout,:),readsPerDecision);

finalEvaluation.available = true;
finalEvaluation.identityPrediction = finalPrediction;
finalEvaluation.identityMetrics = finalMetrics;
finalEvaluation.pufMetrics = finalPUFMetrics;
finalEvaluation.worstConditionPUFReliability = worstFinalPUFReliability;
finalEvaluation.pufByCondition = finalPUFByCondition;
finalEvaluation.sessionIdentityMetrics = finalSessionIdentity;
finalEvaluation.sessionPUFMetrics = finalSessionPUF;
finalEvaluation.checks = evaluateActiveFinalChecks(finalMetrics, ...
    finalPUFMetrics,worstFinalPUFReliability,finalSessionIdentity, ...
    finalSessionPUF,cfg);
finalEvaluation.hypothesisSupported = all(finalEvaluation.checks.Passed);
comparison = compareActiveAgainstPassive(finalEvaluation,cfg);

analysisResults.cfg = cfg;
analysisResults.cores = cores;
analysisResults.featureNames = dataset.featureNames;
analysisResults.features = dataset.features;
analysisResults.responseTensor = dataset.responseTensor;
analysisResults.responseFeatureNames = dataset.responseFeatureNames;
analysisResults.metadata = dataset.metadata;
analysisResults.splits = splits;
analysisResults.identityModel = identityModel;
analysisResults.pufIdentityModel = pufIdentityModel;
analysisResults.validationPrediction = validationPrediction;
analysisResults.validationMetrics = validationMetrics;
analysisResults.testPrediction = testPrediction;
analysisResults.testMetrics = testMetrics;
analysisResults.developmentPrediction = developmentPrediction;
analysisResults.developmentMetrics = developmentMetrics;
analysisResults.pufModel = pufModel;
analysisResults.pufMetrics = pufMetrics;
analysisResults.developmentSessionIdentityMetrics = developmentSessionIdentity;
analysisResults.developmentSessionPUFMetrics = developmentSessionPUF;
analysisResults.finalEvaluation = finalEvaluation;
analysisResults.passiveComparison = comparison;

if cfg.runtime.createFigures
    createActiveFigures(dataset,splits,identityModel,developmentMetrics, ...
        finalEvaluation,analysisResults,cfg);
end
if cfg.runtime.saveMatFile
    save(fullfile(cfg.runtime.resultsDirectory, ...
        'trafodna_active_v3_results.mat'),'analysisResults','-v7.3');
end
if cfg.runtime.saveCsvFile
    featureTable = array2table(dataset.features, ...
        'VariableNames',dataset.featureNames);
    writetable([dataset.metadata featureTable],fullfile( ...
        cfg.runtime.resultsDirectory,'active_response_features.csv'));
    writetable(finalEvaluation.checks,fullfile(cfg.runtime.resultsDirectory, ...
        'active_final_checks.csv'));
    writetable(finalPUFByCondition,fullfile(cfg.runtime.resultsDirectory, ...
        'active_final_puf_by_scenario.csv'));
    writetable(comparison,fullfile(cfg.runtime.resultsDirectory, ...
        'active_passive_comparison.csv'));
    writetable(struct2table(cfg.active.challenges),fullfile( ...
        cfg.runtime.resultsDirectory,'active_challenge_set.csv'));
    writetable(struct2table(cfg.dataset.conditions),fullfile( ...
        cfg.runtime.resultsDirectory,'active_scenario_set.csv'));
end
localPrintSummary(testMetrics,developmentMetrics,pufMetrics, ...
    developmentSessionIdentity,developmentSessionPUF,finalEvaluation, ...
    identityModel,pufIdentityModel,cfg);
end

function [prediction,metrics] = localIdentityEvaluation(model,features,metadata)
[prediction,confidence,distances] = predictIdentity(model,features,metadata);
metrics = computeVerificationMetrics(prediction,metadata.CoreId,confidence, ...
    distances,model.coreIds);
end

function localEnsureDirectories(cfg)
if ~exist(cfg.runtime.resultsDirectory,'dir')
    mkdir(cfg.runtime.resultsDirectory);
end
if ~exist(cfg.runtime.figureDirectory,'dir')
    mkdir(cfg.runtime.figureDirectory);
end
end

function localPrintSummary(testMetrics,developmentMetrics,pufMetrics, ...
    developmentSessionIdentity,developmentSessionPUF,finalEvaluation, ...
    identityModel,pufIdentityModel,cfg)
fprintf('\n--- TrafoDNA V3 Active Result Summary ---\n');
fprintf('Known-scenario identity accuracy      : %.2f %%\n', ...
    100*testMetrics.accuracy);
fprintf('Development identity accuracy         : %.2f %%\n', ...
    100*developmentMetrics.accuracy);
fprintf('Development identity EER              : %.4f\n', ...
    developmentMetrics.eer);
fprintf('Pooled raw PUF reliability            : %.4f\n', ...
    pufMetrics.reliability);
fprintf('Pooled PUF uniqueness                 : %.4f\n', ...
    pufMetrics.uniqueness);
fprintf('Three-sweep development accuracy      : %.2f %%\n', ...
    100*developmentSessionIdentity.accuracy);
fprintf('Three-sweep development EER           : %.4f\n', ...
    developmentSessionIdentity.eer);
fprintf('Three-sweep development PUF reliability: %.4f\n', ...
    developmentSessionPUF.reliability);
fprintf('Selected active identity features     : %d\n', ...
    numel(identityModel.selectedFeatures));
fprintf('Selected raw fingerprint bits         : %d\n', ...
    pufMetrics.numSelectedBits);
fprintf('Strictly eligible fingerprint bits    : %d\n', ...
    pufMetrics.numSelectedEligibleBits);
fprintf('Fallback fingerprint bits             : %d\n', ...
    pufMetrics.numFallbackBits);
fprintf('PUF transform features                : %d\n', ...
    numel(pufIdentityModel.selectedFeatures));
fprintf('PUF nuisance components removed       : %d\n', ...
    pufIdentityModel.nuisanceComponents);
fprintf('Identity tuning strategy              : %s\n', ...
    identityModel.tuningStrategy);

fprintf('\n--- Preregistered V3 Final Holdout ---\n');
fprintf('Single-sweep identity accuracy        : %.2f %%\n', ...
    100*finalEvaluation.identityMetrics.accuracy);
fprintf('Single-sweep identity EER             : %.4f\n', ...
    finalEvaluation.identityMetrics.eer);
fprintf('Raw PUF reliability                   : %.4f\n', ...
    finalEvaluation.pufMetrics.reliability);
fprintf('PUF uniqueness                        : %.4f\n', ...
    finalEvaluation.pufMetrics.uniqueness);
fprintf('Worst-scenario PUF reliability        : %.4f\n', ...
    finalEvaluation.worstConditionPUFReliability);
fprintf('Three-sweep identity accuracy         : %.2f %%\n', ...
    100*finalEvaluation.sessionIdentityMetrics.accuracy);
fprintf('Three-sweep identity EER              : %.4f\n', ...
    finalEvaluation.sessionIdentityMetrics.eer);
fprintf('Three-sweep PUF reliability           : %.4f\n', ...
    finalEvaluation.sessionPUFMetrics.reliability);
fprintf('V3 final checks passed                : %d/%d\n', ...
    sum(finalEvaluation.checks.Passed),height(finalEvaluation.checks));
if finalEvaluation.hypothesisSupported
    decision = 'SUPPORTED';
else
    decision = 'NOT SUPPORTED';
end
fprintf('Preregistered hypothesis decision     : %s\n',decision);
fprintf('Results directory                     : %s\n', ...
    cfg.runtime.resultsDirectory);
fprintf(['Note: V3 remains numerical feasibility evidence, not physical or ' ...
    'cryptographic validation.\n']);
end
