function preparedV32 = main_v32_prepare(cfg)
%MAIN_V32_PREPARE Fit and freeze V3.2 without generating final rows.
%   PREPAREDV32 = MAIN_V32_PREPARE() creates the new 64-core population,
%   fits identity and projected-PUF models on known conditions, evaluates
%   development-only readiness, and saves a sealed model bundle. Scenarios
%   215--218 are not simulated, encoded, evaluated, or saved by this stage.

projectRoot = fileparts(mfilename('fullpath'));
addpath(genpath(projectRoot));
if nargin < 1 || isempty(cfg)
    cfg = defaultV32Config();
end
localValidateProtocol(cfg);
localEnsureDirectories(cfg);
if isfile(cfg.runtime.finalLockFile) || isfile(cfg.runtime.finalResultFile)
    error('TrafoDNA:V32FinalAlreadyOpened', ...
        'V3.2 final has already been opened; preparation is frozen.');
end

contract = buildV32ProtocolContract(cfg);
developmentCfg = buildV32StageConfig(cfg,'development');
rng(cfg.rngSeed,'twister');
if cfg.runtime.verbose
    fprintf(['Starting sealed V3.2 preparation: %d new cores, %d ' ...
        'development scenarios, %d sweeps, %d challenges.\n'], ...
        cfg.dataset.numCores,developmentCfg.dataset.numConditions, ...
        cfg.dataset.repetitions,numel(cfg.active.challenges));
end

cores = repmat(createActiveCore(1,cfg),cfg.dataset.numCores,1);
for coreId = 1:cfg.dataset.numCores
    cores(coreId) = createActiveCore(coreId,cfg);
end
dataset = generateActiveDataset(cores,developmentCfg);
localAssertNoFinalRows(dataset,cfg);
splits = splitDataset(dataset.metadata,developmentCfg);
if any(splits.finalHoldout)
    error('TrafoDNA:V32PreparationFinalLeakage', ...
        'Preparation unexpectedly constructed a final partition.');
end

identityModel = tuneIdentityModel(dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train),dataset.metadata(splits.train,:), ...
    dataset.features(splits.validation,:), ...
    dataset.metadata.CoreId(splits.validation), ...
    dataset.metadata(splits.validation,:),cfg);
[knownPrediction,knownIdentity] = localIdentityEvaluation(identityModel, ...
    dataset.features(splits.test,:),dataset.metadata(splits.test,:));
[developmentPrediction,developmentIdentity] = ...
    localIdentityEvaluation(identityModel,dataset.features(splits.unseen,:), ...
    dataset.metadata(splits.unseen,:));

pufIdentityModel = trainActivePUFTransform( ...
    dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train), ...
    dataset.metadata(splits.train,:),cfg);
pufModel = trainV32ProjectedPUF(dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train),cfg,pufIdentityModel, ...
    dataset.metadata(splits.train,:), ...
    dataset.features(splits.validation,:), ...
    dataset.metadata.CoreId(splits.validation), ...
    dataset.metadata(splits.validation,:),cfg.v32.projection);

pooledMask = splits.test | splits.unseen;
knownPUF = evaluatePUF(pufModel,dataset.features(splits.test,:), ...
    dataset.metadata.CoreId(splits.test),dataset.metadata(splits.test,:));
developmentPUF = evaluatePUF(pufModel, ...
    dataset.features(splits.unseen,:), ...
    dataset.metadata.CoreId(splits.unseen), ...
    dataset.metadata(splits.unseen,:));
pooledPUF = evaluatePUF(pufModel,dataset.features(pooledMask,:), ...
    dataset.metadata.CoreId(pooledMask),dataset.metadata(pooledMask,:));
[worstReliability,pufByCondition] = ...
    computeWorstConditionPUFReliability(pufModel, ...
    dataset.features(pooledMask,:),dataset.metadata.CoreId(pooledMask), ...
    dataset.metadata(pooledMask,:));
readsPerDecision = cfg.session.readsPerDecision;
[~,sessionIdentity] = evaluateIdentitySessions(identityModel, ...
    dataset.features(splits.unseen,:),dataset.metadata(splits.unseen,:), ...
    readsPerDecision);
[sessionPUF,~] = evaluatePUFSessions(pufModel, ...
    dataset.features(pooledMask,:),dataset.metadata(pooledMask,:), ...
    readsPerDecision);
checks = evaluateV32Checks(developmentIdentity,pooledPUF, ...
    worstReliability,sessionIdentity,sessionPUF,pufModel,cfg);

preparedV32.study = cfg.study.name;
preparedV32.protocolVersion = cfg.study.protocolVersion;
preparedV32.status = 'prepared_final_sealed';
preparedV32.cfg = cfg;
preparedV32.contract = contract;
preparedV32.cores = cores;
preparedV32.featureNames = dataset.featureNames;
preparedV32.identityModel = identityModel;
preparedV32.pufIdentityModel = pufIdentityModel;
preparedV32.pufModel = pufModel;
preparedV32.development.knownPrediction = knownPrediction;
preparedV32.development.knownIdentity = knownIdentity;
preparedV32.development.unseenPrediction = developmentPrediction;
preparedV32.development.unseenIdentity = developmentIdentity;
preparedV32.development.knownPUF = knownPUF;
preparedV32.development.unseenPUF = developmentPUF;
preparedV32.development.pooledPUF = pooledPUF;
preparedV32.development.worstConditionPUFReliability = worstReliability;
preparedV32.development.pufByCondition = pufByCondition;
preparedV32.development.sessionIdentity = sessionIdentity;
preparedV32.development.sessionPUF = sessionPUF;
preparedV32.development.checks = checks;
preparedV32.development.readyForFinal = all(checks.Passed);
preparedV32.integrity.developmentRowsGenerated = height(dataset.metadata);
preparedV32.integrity.enrollmentRowsUsed = sum(splits.train);
preparedV32.integrity.validationRowsUsed = sum(splits.validation);
preparedV32.integrity.knownTestRowsUsed = sum(splits.test);
preparedV32.integrity.unseenDevelopmentRowsUsed = sum(splits.unseen);
preparedV32.integrity.finalRowsGenerated = 0;
preparedV32.integrity.finalRowsUsed = 0;
preparedV32.integrity.finalConditionIdsPresent = zeros(1,0);

save(cfg.runtime.preparedBundleFile,'preparedV32','-v7.3');
if cfg.runtime.saveCsvFile
    writetable(checks,fullfile(cfg.runtime.developmentDirectory, ...
        'v32_development_checks.csv'));
    writetable(pufByCondition,fullfile(cfg.runtime.developmentDirectory, ...
        'v32_development_puf_by_condition.csv'));
    writetable(pufModel.selectedBitsTable, ...
        fullfile(cfg.runtime.developmentDirectory, ...
        'v32_frozen_projected_bits.csv'));
    writetable(struct2table(cfg.dataset.conditions), ...
        fullfile(cfg.runtime.resultsDirectory,'v32_scenario_contract.csv'));
end
localPrintPreparation(preparedV32);
end

function [prediction,metrics] = localIdentityEvaluation(model,features,metadata)
[prediction,confidence,distances] = predictIdentity(model,features,metadata);
metrics = computeVerificationMetrics(prediction,metadata.CoreId,confidence, ...
    distances,model.coreIds);
end

function localValidateProtocol(cfg)
requiredStatus = 'preregistered_final_sealed';
if ~strcmp(cfg.study.protocolVersion,'3.2.0-preregistered') || ...
        ~strcmp(cfg.study.status,requiredStatus)
    error('TrafoDNA:InvalidV32ProtocolStatus', ...
        'V3.2 preparation requires the sealed preregistered protocol.');
end
if cfg.dataset.numCores ~= 64 || cfg.rngSeed ~= 20260831 || ...
        ~isequal(cfg.dataset.finalHoldoutConditionIds,215:218) || ...
        ~cfg.dataset.seedByConditionId
    error('TrafoDNA:InvalidV32ProtocolContract', ...
        'The frozen V3.2 population, seed, or final IDs changed.');
end
if ~isempty(intersect(cfg.dataset.finalHoldoutConditionIds,115:118))
    error('TrafoDNA:ReusedV3FinalCondition', ...
        'V3.2 may not reuse observed V3 final conditions.');
end
end

function localAssertNoFinalRows(dataset,cfg)
if any(dataset.metadata.IsFinalHoldoutCondition) || ...
        any(ismember(dataset.metadata.ConditionId, ...
        cfg.dataset.finalHoldoutConditionIds))
    error('TrafoDNA:V32PreparationFinalLeakage', ...
        'Final rows were generated during V3.2 preparation.');
end
end

function localEnsureDirectories(cfg)
directories = {cfg.runtime.resultsDirectory, ...
    cfg.runtime.developmentDirectory,cfg.runtime.finalDirectory, ...
    cfg.runtime.figureDirectory};
for k = 1:numel(directories)
    if ~exist(directories{k},'dir')
        mkdir(directories{k});
    end
end
end

function localPrintPreparation(prepared)
development = prepared.development;
fprintf('\n--- TrafoDNA V3.2 Sealed Preparation ---\n');
fprintf('New virtual-core population             : %d\n', ...
    prepared.cfg.dataset.numCores);
fprintf('Development rows generated              : %d\n', ...
    prepared.integrity.developmentRowsGenerated);
fprintf('Final rows generated / used             : %d / %d\n', ...
    prepared.integrity.finalRowsGenerated, ...
    prepared.integrity.finalRowsUsed);
fprintf('Unseen-development identity accuracy    : %.2f %%\n', ...
    100*development.unseenIdentity.accuracy);
fprintf('Unseen-development identity EER         : %.4f\n', ...
    development.unseenIdentity.eer);
fprintf('Selected projected fingerprint bits     : %d\n', ...
    prepared.pufModel.numSelectedEligibleBits);
fprintf('Pooled development PUF reliability      : %.4f\n', ...
    development.pooledPUF.reliability);
fprintf('Pooled development PUF uniqueness       : %.4f\n', ...
    development.pooledPUF.uniqueness);
fprintf('Worst-development-scenario reliability  : %.4f\n', ...
    development.worstConditionPUFReliability);
fprintf('Three-sweep development identity        : %.2f %%\n', ...
    100*development.sessionIdentity.accuracy);
fprintf('Three-sweep development PUF reliability : %.4f\n', ...
    development.sessionPUF.reliability);
fprintf('Maximum selected-bit correlation        : %.4f\n', ...
    prepared.pufModel.maximumSelectedCorrelation);
fprintf('Development readiness checks            : %d/%d\n', ...
    sum(development.checks.Passed),height(development.checks));
fprintf('Prepared bundle                         : %s\n', ...
    prepared.cfg.runtime.preparedBundleFile);
fprintf(['Status: FINAL REMAINS SEALED. Do not run MAIN_V32_FINAL until ' ...
    'the preparation record has been reviewed and archived.\n']);
end
