function report = createV32FinalReport(preparedV32,finalV32,options)
%CREATEV32FINALREPORT Build a read-only V3.2 evidence report.
%   The function validates the frozen contract and stored metrics, then
%   writes tables, figures, Markdown, and Word-readable HTML. It never fits
%   a model, generates a scenario, or modifies either locked input result.

if nargin < 3 || isempty(options)
    options = struct();
end
options = localOptions(options,preparedV32);
recomputedChecks = localValidateInputs(preparedV32,finalV32);

summaryTable = localSummaryTable(preparedV32,finalV32);
scenarioTable = localScenarioTable(finalV32);
[perBitTable,referenceCorrelation] = localPerBitTable(finalV32);
integrityTable = localIntegrityTable(preparedV32,finalV32);

if finalV32.hypothesisSupported
    decision = 'SUPPORTED';
else
    decision = 'NOT SUPPORTED';
end
report.study = finalV32.study;
report.protocolVersion = finalV32.protocolVersion;
report.status = 'locked_final_report_generated';
report.decision = decision;
report.hypothesisSupported = finalV32.hypothesisSupported;
report.integrityVerified = true;
report.storedChecksReproduced = isequal(recomputedChecks.Passed, ...
    finalV32.checks.Passed);
report.summaryTable = summaryTable;
report.scenarioTable = scenarioTable;
report.perBitTable = perBitTable;
report.referenceBitCorrelation = referenceCorrelation;
report.integrityTable = integrityTable;
report.evidenceManifest = options.evidenceManifest;
report.outputDirectory = options.outputDirectory;
report.figureFiles = cell(0,1);
report.outputFiles = struct();

if options.saveFiles
    localEnsureDirectory(options.outputDirectory);
    localEnsureDirectory(options.figureDirectory);
end
if options.createFigures
    if ~options.saveFiles
        error('TrafoDNA:V32ReportFigureDestinationRequired', ...
            'Figure creation requires saveFiles=true.');
    end
    report.figureFiles = localCreateFigures(preparedV32,finalV32, ...
        scenarioTable,perBitTable,referenceCorrelation,options);
end
if options.saveFiles
    report = localWriteReportFiles(report,preparedV32,finalV32,options);
end
if options.verbose
    localPrintReport(report);
end
end

function options = localOptions(options,prepared)
defaults.outputDirectory = fullfile( ...
    prepared.cfg.runtime.resultsDirectory,'report');
defaults.figureVisible = 'off';
defaults.createFigures = true;
defaults.saveFiles = true;
defaults.verbose = true;
defaults.evidenceManifest = table();
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(options,names{k})
        options.(names{k}) = defaults.(names{k});
    end
end
options.createFigures = logical(options.createFigures);
options.saveFiles = logical(options.saveFiles);
options.verbose = logical(options.verbose);
options.outputDirectory = char(options.outputDirectory);
options.figureDirectory = fullfile(options.outputDirectory,'figures');
if ~istable(options.evidenceManifest)
    error('TrafoDNA:InvalidV32EvidenceManifest', ...
        'The evidence manifest must be a table.');
end
end

function recomputed = localValidateInputs(prepared,finalResult)
preparedFields = {'cfg','contract','development','pufModel','integrity'};
finalFields = {'study','protocolVersion','status','contract','metadata', ...
    'identityPrediction','identityMetrics','pufMetrics', ...
    'worstConditionPUFReliability','pufByCondition', ...
    'sessionIdentityMetrics','sessionPUFMetrics','pufModel','checks', ...
    'hypothesisSupported','integrity'};
localRequireFields(prepared,preparedFields,'prepared bundle');
localRequireFields(finalResult,finalFields,'locked final result');
if ~strcmp(finalResult.status,'locked_final_observed') || ...
        ~isequaln(prepared.contract,finalResult.contract) || ...
        ~isequaln(prepared.contract, ...
        buildV32ProtocolContract(prepared.cfg))
    error('TrafoDNA:V32ReportContractMismatch', ...
        'Prepared and final protocol contracts do not agree.');
end
if prepared.integrity.finalRowsGenerated ~= 0 || ...
        prepared.integrity.finalRowsUsed ~= 0
    error('TrafoDNA:V32ReportPreparationLeakage', ...
        'Preparation does not preserve a zero-final-row state.');
end
if ~istable(finalResult.metadata) || ...
        numel(finalResult.identityPrediction) ~= height(finalResult.metadata)
    error('TrafoDNA:V32ReportDimensionMismatch', ...
        'Final metadata and predictions have inconsistent dimensions.');
end
rowCount = height(finalResult.metadata);
observedIds = unique(finalResult.metadata.ConditionId,'stable')';
expectedRows = prepared.cfg.dataset.numCores* ...
    numel(prepared.cfg.dataset.finalHoldoutConditionIds)* ...
    prepared.cfg.dataset.repetitions;
if finalResult.integrity.finalRowsGenerated ~= rowCount || ...
        finalResult.integrity.finalRowsUsed ~= rowCount || ...
        finalResult.integrity.preparationFinalRowsUsed ~= 0 || ...
        ~isequal(finalResult.integrity.finalConditionIds,observedIds) || ...
        ~isequal(observedIds, ...
        prepared.cfg.dataset.finalHoldoutConditionIds) || ...
        rowCount ~= expectedRows || ...
        ~all(finalResult.metadata.IsFinalHoldoutCondition) || ...
        any(finalResult.metadata.IsUnseenCondition)
    error('TrafoDNA:V32ReportIntegrityMismatch', ...
        'Stored V3.2 final-row integrity evidence is inconsistent.');
end
if ~istable(finalResult.checks) || height(finalResult.checks) ~= 10 || ...
        ~istable(prepared.development.checks) || ...
        height(prepared.development.checks) ~= 10
    error('TrafoDNA:V32ReportInvalidChecks', ...
        'Both development and final reports require ten checks.');
end
recomputed = evaluateV32Checks(finalResult.identityMetrics, ...
    finalResult.pufMetrics,finalResult.worstConditionPUFReliability, ...
    finalResult.sessionIdentityMetrics,finalResult.sessionPUFMetrics, ...
    finalResult.pufModel,prepared.cfg);
if max(abs(recomputed.Current-finalResult.checks.Current)) > 1e-12 || ...
        ~isequal(recomputed.Passed,finalResult.checks.Passed) || ...
        finalResult.hypothesisSupported ~= all(finalResult.checks.Passed)
    error('TrafoDNA:V32ReportCheckMismatch', ...
        'Stored final checks cannot be reproduced from locked metrics.');
end
if ~isequal(prepared.pufModel.referenceBits, ...
        finalResult.pufModel.referenceBits) || ...
        ~isequal(prepared.pufModel.selectedCandidateIndices, ...
        finalResult.pufModel.selectedCandidateIndices)
    error('TrafoDNA:V32ReportFrozenModelMismatch', ...
        'The final PUF model differs from the prepared frozen model.');
end
end

function localRequireFields(value,fields,label)
for k = 1:numel(fields)
    if ~isfield(value,fields{k})
        error('TrafoDNA:V32ReportMissingField', ...
            '%s is missing field "%s".',label,fields{k});
    end
end
end

function summary = localSummaryTable(prepared,finalResult)
developmentChecks = prepared.development.checks;
finalChecks = finalResult.checks;
if ~isequal(developmentChecks.Metric,finalChecks.Metric)
    error('TrafoDNA:V32ReportMetricOrderChanged', ...
        'Development and final metric names do not match.');
end
summary = table(finalChecks.Metric,developmentChecks.Current, ...
    finalChecks.Current,finalChecks.Target,developmentChecks.Passed, ...
    finalChecks.Passed,'VariableNames',{'Metric','Development', ...
    'LockedFinal','Target','DevelopmentPassed','FinalPassed'});
end

function scenarioTable = localScenarioTable(finalResult)
conditionIds = unique(finalResult.metadata.ConditionId,'stable');
sampleCount = zeros(numel(conditionIds),1);
identityAccuracy = zeros(numel(conditionIds),1);
pufReliability = zeros(numel(conditionIds),1);
for k = 1:numel(conditionIds)
    selected = finalResult.metadata.ConditionId == conditionIds(k);
    sampleCount(k) = sum(selected);
    identityAccuracy(k) = mean(finalResult.identityPrediction(selected) == ...
        finalResult.metadata.CoreId(selected));
    tableRow = finalResult.pufByCondition.ConditionId == conditionIds(k);
    if nnz(tableRow) ~= 1
        error('TrafoDNA:V32ReportMissingScenarioMetric', ...
            'Final PUF reliability is missing for condition %d.', ...
            conditionIds(k));
    end
    pufReliability(k) = finalResult.pufByCondition.Reliability(tableRow);
end
scenarioTable = table(conditionIds,sampleCount,identityAccuracy, ...
    pufReliability,'VariableNames',{'ConditionId','SampleCount', ...
    'IdentityAccuracy','PUFReliability'});
end

function [perBitTable,correlation] = localPerBitTable(finalResult)
bits = logical(finalResult.pufMetrics.testBits);
referenceBits = logical(finalResult.pufModel.referenceBits);
numBits = size(referenceBits,2);
if size(bits,1) ~= height(finalResult.metadata) || ...
        size(bits,2) ~= numBits || numBits < 1
    error('TrafoDNA:V32ReportInvalidBits', ...
        'Final bit responses do not match the frozen reference width.');
end
agreement = false(size(bits));
for row = 1:size(bits,1)
    corePosition = find(finalResult.pufModel.coreIds == ...
        finalResult.metadata.CoreId(row),1);
    if isempty(corePosition)
        error('TrafoDNA:V32ReportUnknownCore', ...
            'A final response does not have an enrolled reference.');
    end
    agreement(row,:) = bits(row,:) == referenceBits(corePosition,:);
end
correlation = corrcoef(double(referenceBits));
correlation(~isfinite(correlation)) = 0;
correlation(1:numBits+1:end) = 1;
offDiagonal = abs(correlation);
offDiagonal(1:numBits+1:end) = 0;

bitNumber = (1:numBits)';
candidateIndex = localSelectedColumn(finalResult.pufModel, ...
    'CandidateIndex',numBits);
enrollmentReliability = localSelectedColumn(finalResult.pufModel, ...
    'EnrollmentReliability',numBits);
validationReliability = localSelectedColumn(finalResult.pufModel, ...
    'ValidationReliability',numBits);
worstKnownReliability = localSelectedColumn(finalResult.pufModel, ...
    'WorstKnownConditionReliability',numBits);
selectionScore = localSelectedColumn(finalResult.pufModel, ...
    'SelectionScore',numBits);
finalReliability = mean(agreement,1)';
referenceOneRate = mean(referenceBits,1)';
finalOneRate = mean(bits,1)';
maximumAbsCorrelation = max(offDiagonal,[],2);
perBitTable = table(bitNumber,candidateIndex,enrollmentReliability, ...
    validationReliability,worstKnownReliability,selectionScore, ...
    finalReliability,referenceOneRate,finalOneRate, ...
    maximumAbsCorrelation,'VariableNames',{'Bit','CandidateIndex', ...
    'EnrollmentReliability','ValidationReliability', ...
    'WorstKnownConditionReliability','SelectionScore', ...
    'FinalReliability','ReferenceOneRate','FinalOneRate', ...
    'MaximumAbsReferenceCorrelation'});
end

function values = localSelectedColumn(model,variableName,count)
values = NaN(count,1);
if isfield(model,'selectedBitsTable') && istable(model.selectedBitsTable) && ...
        height(model.selectedBitsTable) == count && ...
        ismember(variableName,model.selectedBitsTable.Properties.VariableNames)
    values = model.selectedBitsTable.(variableName);
    values = values(:);
end
end

function integrityTable = localIntegrityTable(prepared,finalResult)
if finalResult.hypothesisSupported
    decision = 'SUPPORTED';
else
    decision = 'NOT SUPPORTED';
end
item = {'Protocol version';'Final status';'Decision'; ...
    'Development rows generated';'Preparation final rows generated'; ...
    'Preparation final rows used';'Final rows generated'; ...
    'Final rows used';'Final condition IDs';'Selected projected bits'};
value = {finalResult.protocolVersion;finalResult.status;decision; ...
    sprintf('%d',prepared.integrity.developmentRowsGenerated); ...
    sprintf('%d',prepared.integrity.finalRowsGenerated); ...
    sprintf('%d',prepared.integrity.finalRowsUsed); ...
    sprintf('%d',finalResult.integrity.finalRowsGenerated); ...
    sprintf('%d',finalResult.integrity.finalRowsUsed); ...
    strtrim(sprintf('%d ',finalResult.integrity.finalConditionIds)); ...
    sprintf('%d',finalResult.pufMetrics.numSelectedEligibleBits)};
integrityTable = table(item,value,'VariableNames',{'Item','Value'});
end

function figureFiles = localCreateFigures(prepared,finalResult, ...
    scenarioTable,perBitTable,correlation,options)
figureNames = {'01_v32_development_vs_final.png'; ...
    '02_v32_final_confusion_matrix.png';'03_v32_final_roc.png'; ...
    '04_v32_final_hamming_distances.png'; ...
    '05_v32_final_per_scenario.png'; ...
    '06_v32_final_per_bit_reliability.png'; ...
    '07_v32_reference_bit_correlation.png'};
figureFiles = cellfun(@(name) fullfile(options.figureDirectory,name), ...
    figureNames,'UniformOutput',false);

development = prepared.development.checks.Current;
lockedFinal = finalResult.checks.Current;
selected = [1 3 6 7 9];
labels = {'Identity accuracy','PUF reliability','Worst PUF scenario', ...
    '3-sweep identity','3-sweep PUF'};
fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 1050 560]);
bar(100*[development(selected) lockedFinal(selected)]);
grid on; ylim([0 105]); ylabel('Performance (%)');
set(gca,'XTick',1:numel(labels),'XTickLabel',labels);
xtickangle(15);
legend({'Development','Locked final'},'Location','southoutside', ...
    'Orientation','horizontal');
title('TrafoDNA V3.2 development and locked-final performance');
localSaveFigure(fh,figureFiles{1});

fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 760 680]);
imagesc(finalResult.identityMetrics.confusionMatrix); axis image; colorbar;
xlabel('Predicted virtual core'); ylabel('True virtual core');
title(sprintf('V3.2 locked-final identity confusion matrix (%.2f%%)', ...
    100*finalResult.identityMetrics.accuracy));
localSaveFigure(fh,figureFiles{2});

metrics = finalResult.identityMetrics;
fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 760 600]);
plot(metrics.falseAcceptRate,metrics.trueAcceptRate,'LineWidth',1.7); hold on;
plot(metrics.far(metrics.eerIndex),1-metrics.frr(metrics.eerIndex), ...
    'ro','MarkerFaceColor','r');
plot([0 1],[0 1],'k--'); grid on; axis([0 1 0 1]);
xlabel('False acceptance rate'); ylabel('True acceptance rate');
title(sprintf('V3.2 locked-final verification ROC (EER = %.4f)', ...
    metrics.eer));
legend({'ROC','EER operating point','Chance'},'Location','southeast');
localSaveFigure(fh,figureFiles{3});

fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 800 600]); hold on;
histogram(finalResult.pufMetrics.intraHammingDistance,30, ...
    'Normalization','probability','FaceAlpha',0.70);
histogram(finalResult.pufMetrics.interHammingDistance,30, ...
    'Normalization','probability','FaceAlpha',0.55);
grid on; xlim([0 1]); xlabel('Normalized Hamming distance');
ylabel('Probability');
title(sprintf('V3.2 locked-final projected fingerprint (%d bits)', ...
    finalResult.pufMetrics.numSelectedBits));
legend({'Intra-core','Inter-core'},'Location','best');
localSaveFigure(fh,figureFiles{4});

fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 900 700]);
subplot(2,1,1);
bar(scenarioTable.ConditionId,100*scenarioTable.IdentityAccuracy, ...
    'FaceColor',[0.22 0.55 0.75]); hold on;
yline(100*prepared.cfg.benchmark.v32Targets.identityAccuracy,'r--', ...
    'Frozen target');
grid on; ylim([0 105]); ylabel('Identity accuracy (%)');
title('Locked-final identity accuracy by scenario');
subplot(2,1,2);
bar(scenarioTable.ConditionId,100*scenarioTable.PUFReliability, ...
    'FaceColor',[0.34 0.68 0.48]); hold on;
yline(100*prepared.cfg.benchmark.v32Targets. ...
    worstConditionPUFReliability,'r--','Frozen target');
grid on; ylim([0 105]); xlabel('Final scenario ID');
ylabel('PUF reliability (%)');
title('Locked-final projected-PUF reliability by scenario');
localSaveFigure(fh,figureFiles{5});

[sortedReliability,order] = sort(perBitTable.FinalReliability,'ascend');
fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 900 560]);
plot(1:height(perBitTable),100*sortedReliability,'o-', ...
    'LineWidth',1.2,'MarkerSize',4); hold on;
yline(100*prepared.cfg.benchmark.v32Targets.pufReliability, ...
    'r--','Frozen pooled target');
grid on; ylim([80 101]); xlabel('Selected bit, sorted by final reliability');
ylabel('Final reliability (%)');
title('V3.2 locked-final reliability of each selected projected bit');
if isempty(order)
    warning('TrafoDNA:EmptyV32BitOrder','No selected bit order was found.');
end
localSaveFigure(fh,figureFiles{6});

fh = figure('Visible',options.figureVisible,'Color','w', ...
    'Position',[100 100 760 680]);
imagesc(abs(correlation)); axis image; colorbar; caxis([0 1]);
xlabel('Selected projected bit'); ylabel('Selected projected bit');
title(sprintf(['Absolute enrollment-reference correlation ' ...
    '(maximum off-diagonal = %.2f)'], ...
    finalResult.pufModel.maximumSelectedCorrelation));
localSaveFigure(fh,figureFiles{7});
end

function report = localWriteReportFiles(report,prepared,finalResult,options)
paths.summaryCsv = fullfile(options.outputDirectory, ...
    'v32_final_report_summary.csv');
paths.scenarioCsv = fullfile(options.outputDirectory, ...
    'v32_final_scenario_metrics.csv');
paths.perBitCsv = fullfile(options.outputDirectory, ...
    'v32_final_per_bit_metrics.csv');
paths.correlationCsv = fullfile(options.outputDirectory, ...
    'v32_reference_bit_correlation.csv');
paths.integrityCsv = fullfile(options.outputDirectory, ...
    'v32_final_integrity.csv');
paths.manifestCsv = fullfile(options.outputDirectory, ...
    'v32_evidence_manifest.csv');
paths.markdown = fullfile(options.outputDirectory,'V32_FINAL_OUTCOME.md');
paths.html = fullfile(options.outputDirectory,'V32_FINAL_REPORT.html');
paths.mat = fullfile(options.outputDirectory,'v32_final_report.mat');

writetable(report.summaryTable,paths.summaryCsv);
writetable(report.scenarioTable,paths.scenarioCsv);
writetable(report.perBitTable,paths.perBitCsv);
bitNames = arrayfun(@(k) sprintf('Bit%02d',k), ...
    1:size(report.referenceBitCorrelation,2),'UniformOutput',false);
correlationTable = array2table(report.referenceBitCorrelation, ...
    'VariableNames',bitNames,'RowNames',bitNames);
writetable(correlationTable,paths.correlationCsv,'WriteRowNames',true);
writetable(report.integrityTable,paths.integrityCsv);
if ~isempty(report.evidenceManifest)
    writetable(report.evidenceManifest,paths.manifestCsv);
end
localWriteMarkdown(paths.markdown,report,prepared,finalResult);
localWriteHtml(paths.html,report,prepared,finalResult);
report.outputFiles = paths;
save(paths.mat,'report','-v7');
end

function localWriteMarkdown(fileName,report,prepared,finalResult)
fileId = localOpenTextFile(fileName);
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId,'# TrafoDNA V3.2 Locked Final Outcome\n\n');
fprintf(fileId,'## Decision\n\n');
fprintf(fileId,'**Preregistered numerical hypothesis: %s (%d/10 gates).**\n\n', ...
    report.decision,sum(report.summaryTable.FinalPassed));
fprintf(fileId,['The frozen projected challenge-response representation ' ...
    'was evaluated on a new 64-core virtual population and locked final ' ...
    'scenarios 215--218.\n\n']);
fprintf(fileId,'## Development and locked-final metrics\n\n');
fprintf(fileId,['| Metric | Development | Locked final | Target | ' ...
    'Final result |\n']);
fprintf(fileId,'|---|---:|---:|---|:---:|\n');
for k = 1:height(report.summaryTable)
    outcome = localPassFail(report.summaryTable.FinalPassed(k));
    fprintf(fileId,'| %s | %s | %s | %s | %s |\n', ...
        report.summaryTable.Metric{k}, ...
        localFormatMetric(k,report.summaryTable.Development(k)), ...
        localFormatMetric(k,report.summaryTable.LockedFinal(k)), ...
        report.summaryTable.Target{k},outcome);
end
fprintf(fileId,'\n## Integrity record\n\n');
for k = 1:height(report.integrityTable)
    fprintf(fileId,'- %s: `%s`\n',report.integrityTable.Item{k}, ...
        report.integrityTable.Value{k});
end
fprintf(fileId,'\n## Evidence-file SHA-256\n\n');
if isempty(report.evidenceManifest)
    fprintf(fileId,'No external evidence manifest was supplied.\n');
else
    for k = 1:height(report.evidenceManifest)
        fprintf(fileId,'- `%s`: `%s`\n', ...
            report.evidenceManifest.FileName{k}, ...
            report.evidenceManifest.SHA256{k});
    end
end
fprintf(fileId,'\n## Figures\n\n');
captions = localFigureCaptions();
for k = 1:numel(report.figureFiles)
    [~,base,extension] = fileparts(report.figureFiles{k});
    fprintf(fileId,'![%s](figures/%s%s)\n\n',captions{k},base,extension);
end
fprintf(fileId,'## Interpretation\n\n');
fprintf(fileId,['V3.2 passed all ten frozen gates. Final identity accuracy ' ...
    'was %.2f%% with EER %.4f. The %d-bit projected response achieved ' ...
    'reliability %.4f, uniqueness %.4f, worst-scenario reliability ' ...
    '%.4f, and three-sweep reliability %.4f.\n\n'], ...
    100*finalResult.identityMetrics.accuracy,finalResult.identityMetrics.eer, ...
    finalResult.pufMetrics.numSelectedBits, ...
    finalResult.pufMetrics.reliability,finalResult.pufMetrics.uniqueness, ...
    finalResult.worstConditionPUFReliability, ...
    finalResult.sessionPUFMetrics.reliability);
fprintf(fileId,['This supports numerical feasibility only. It is not ' ...
    'physical transformer validation, proof of independent key entropy, ' ...
    'or cryptographic security validation. Maximum selected-bit reference ' ...
    'correlation was %.4f.\n'], ...
    finalResult.pufModel.maximumSelectedCorrelation);
fprintf(fileId,'\nPreparation final rows used: %d.\n', ...
    prepared.integrity.finalRowsUsed);
clear cleanup
end

function localWriteHtml(fileName,report,prepared,finalResult)
fileId = localOpenTextFile(fileName);
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId,['<!doctype html><html><head><meta charset="utf-8">' ...
    '<title>TrafoDNA V3.2 Final Report</title><style>' ...
    'body{font-family:Arial,sans-serif;max-width:1100px;margin:36px auto;' ...
    'color:#1f2933;line-height:1.5}h1,h2{color:#17365d}' ...
    '.decision{padding:14px 18px;background:#e8f5e9;border-left:5px solid ' ...
    '#2e7d32;font-weight:bold}table{border-collapse:collapse;width:100%%;' ...
    'margin:14px 0 24px}th,td{border:1px solid #c8d1da;padding:8px;' ...
    'text-align:left}th{background:#eef3f7}.pass{color:#1b7f3a;' ...
    'font-weight:bold}img{max-width:100%%;height:auto;border:1px solid ' ...
    '#d8dee4;margin:10px 0 28px}code{font-size:90%%}' ...
    '</style></head><body>']);
fprintf(fileId,'<h1>TrafoDNA V3.2 Locked Final Outcome</h1>');
fprintf(fileId,['<p class="decision">Preregistered numerical hypothesis: ' ...
    '%s (%d/10 gates)</p>'],report.decision, ...
    sum(report.summaryTable.FinalPassed));
fprintf(fileId,['<p>The frozen projected challenge-response representation ' ...
    'was evaluated on a new 64-core virtual population and locked final ' ...
    'scenarios 215&ndash;218.</p>']);
fprintf(fileId,['<h2>Development and locked-final metrics</h2><table><tr>' ...
    '<th>Metric</th><th>Development</th><th>Locked final</th>' ...
    '<th>Target</th><th>Result</th></tr>']);
for k = 1:height(report.summaryTable)
    fprintf(fileId,['<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td>' ...
        '<td class="pass">%s</td></tr>'],report.summaryTable.Metric{k}, ...
        localFormatMetric(k,report.summaryTable.Development(k)), ...
        localFormatMetric(k,report.summaryTable.LockedFinal(k)), ...
        report.summaryTable.Target{k}, ...
        localPassFail(report.summaryTable.FinalPassed(k)));
end
fprintf(fileId,'</table><h2>Integrity record</h2><table>');
for k = 1:height(report.integrityTable)
    fprintf(fileId,'<tr><th>%s</th><td>%s</td></tr>', ...
        report.integrityTable.Item{k},report.integrityTable.Value{k});
end
fprintf(fileId,'</table><h2>Evidence-file SHA-256</h2><table>');
for k = 1:height(report.evidenceManifest)
    fprintf(fileId,'<tr><th>%s</th><td><code>%s</code></td></tr>', ...
        report.evidenceManifest.FileName{k}, ...
        report.evidenceManifest.SHA256{k});
end
fprintf(fileId,'</table><h2>Figures</h2>');
captions = localFigureCaptions();
for k = 1:numel(report.figureFiles)
    [~,base,extension] = fileparts(report.figureFiles{k});
    fprintf(fileId,'<h3>%s</h3><img src="figures/%s%s" alt="%s">', ...
        captions{k},base,extension,captions{k});
end
fprintf(fileId,['<h2>Interpretation</h2><p>V3.2 passed all ten frozen ' ...
    'gates. Final identity accuracy was %.2f%% with EER %.4f. The %d-bit ' ...
    'projected response achieved reliability %.4f, uniqueness %.4f, ' ...
    'worst-scenario reliability %.4f, and three-sweep reliability ' ...
    '%.4f.</p>'],100*finalResult.identityMetrics.accuracy, ...
    finalResult.identityMetrics.eer,finalResult.pufMetrics.numSelectedBits, ...
    finalResult.pufMetrics.reliability,finalResult.pufMetrics.uniqueness, ...
    finalResult.worstConditionPUFReliability, ...
    finalResult.sessionPUFMetrics.reliability);
fprintf(fileId,['<p><strong>Scientific boundary:</strong> This supports ' ...
    'numerical feasibility only. It is not physical transformer validation, ' ...
    'proof of independent key entropy, or cryptographic security ' ...
    'validation. Maximum selected-bit reference correlation was %.4f. ' ...
    'Preparation final rows used: %d.</p>'], ...
    finalResult.pufModel.maximumSelectedCorrelation, ...
    prepared.integrity.finalRowsUsed);
fprintf(fileId,'</body></html>');
clear cleanup
end

function captions = localFigureCaptions()
captions = {'Development versus locked-final performance'; ...
    'Locked-final identity confusion matrix'; ...
    'Locked-final identity verification ROC'; ...
    'Intra-core and inter-core Hamming distances'; ...
    'Identity and PUF performance by final scenario'; ...
    'Final reliability of each selected projected bit'; ...
    'Absolute correlation among selected reference bits'};
end

function text = localFormatMetric(row,value)
if row == 5
    text = sprintf('%d',round(value));
else
    text = sprintf('%.4f',value);
end
end

function text = localPassFail(value)
if value
    text = 'PASS';
else
    text = 'FAIL';
end
end

function fileId = localOpenTextFile(fileName)
[fileId,message] = fopen(fileName,'w');
if fileId < 0
    error('TrafoDNA:V32ReportWriteFailed', ...
        'Could not write "%s": %s',fileName,message);
end
end

function localEnsureDirectory(directory)
if ~exist(directory,'dir')
    mkdir(directory);
end
end

function localSaveFigure(figureHandle,fileName)
set(figureHandle,'PaperPositionMode','auto');
print(figureHandle,fileName,'-dpng','-r200');
close(figureHandle);
end

function localPrintReport(report)
fprintf('\n--- TrafoDNA V3.2 Locked Final Report Package ---\n');
fprintf('Stored final checks reproduced          : YES\n');
fprintf('Integrity record verified               : YES\n');
fprintf('Final decision                          : %s\n',report.decision);
fprintf('Checks passed                           : %d/%d\n', ...
    sum(report.summaryTable.FinalPassed),height(report.summaryTable));
fprintf('Figures generated                       : %d\n', ...
    numel(report.figureFiles));
if isfield(report.outputFiles,'markdown')
    fprintf('Markdown report                         : %s\n', ...
        report.outputFiles.markdown);
    fprintf('Word-readable HTML report               : %s\n', ...
        report.outputFiles.html);
end
fprintf(['Note: Reporting was read-only; no model fitting or final-row ' ...
    'generation was performed.\n']);
end
