function study = analyzeV32ProjectedPUF(activeResults,options)
%ANALYZEV32PROJECTEDPUF Run exploratory V3.2 projected-bit development.
%   Training uses enrollment rows, candidate screening uses validation rows,
%   and reporting uses only known-test plus unseen-development rows. Locked
%   V3 final rows are excluded from fitting, selection, and evaluation.

if nargin < 2 || isempty(options)
    options = struct();
end
localValidateResults(activeResults);
cfg = activeResults.cfg;
options = localOptions(options,cfg);
splits = activeResults.splits;
trainMask = logical(splits.train(:));
validationMask = logical(splits.validation(:));
knownTestMask = logical(splits.test(:));
unseenMask = logical(splits.unseen(:));
developmentMask = knownTestMask | unseenMask;
finalMask = logical(splits.finalHoldout(:));
membership = double(trainMask)+double(validationMask)+ ...
    double(developmentMask)+double(finalMask);
if any(membership > 1)
    error('TrafoDNA:V32ProjectionPartitionLeakage', ...
        'V3.2 projected-bit partitions overlap.');
end
if ~any(trainMask) || ~any(validationMask) || ~any(developmentMask)
    error('TrafoDNA:V32ProjectionEmptyPartition', ...
        'Enrollment, validation, and development rows must be nonempty.');
end

features = activeResults.features;
metadata = activeResults.metadata;
pufModel = trainV32ProjectedPUF(features(trainMask,:), ...
    metadata.CoreId(trainMask),cfg,activeResults.pufIdentityModel, ...
    metadata(trainMask,:),features(validationMask,:), ...
    metadata.CoreId(validationMask),metadata(validationMask,:),options);

knownTestMetrics = evaluatePUF(pufModel,features(knownTestMask,:), ...
    metadata.CoreId(knownTestMask),metadata(knownTestMask,:));
unseenMetrics = evaluatePUF(pufModel,features(unseenMask,:), ...
    metadata.CoreId(unseenMask),metadata(unseenMask,:));
pooledMetrics = evaluatePUF(pufModel,features(developmentMask,:), ...
    metadata.CoreId(developmentMask),metadata(developmentMask,:));
[worstDevelopmentReliability,conditionTable] = ...
    computeWorstConditionPUFReliability(pufModel, ...
    features(developmentMask,:),metadata.CoreId(developmentMask), ...
    metadata(developmentMask,:));
[sessionMetrics,~] = evaluatePUFSessions(pufModel, ...
    features(developmentMask,:),metadata(developmentMask,:), ...
    cfg.session.readsPerDecision);

uniquenessRange = cfg.benchmark.activeTargets.pufUniquenessRange;
check = {'Selected raw projected bits'; ...
    'Pooled development reliability'; ...
    'Pooled development uniqueness'; ...
    'Worst-development-scenario reliability'; ...
    'Three-sweep development reliability'; ...
    'Maximum selected-bit correlation'; ...
    'Locked final rows excluded'};
current = [pufModel.numSelectedEligibleBits; ...
    pooledMetrics.reliability;pooledMetrics.uniqueness; ...
    worstDevelopmentReliability;sessionMetrics.reliability; ...
    pufModel.maximumSelectedCorrelation;0];
required = [pufModel.targetBits;cfg.benchmark.activeTargets.pufReliability; ...
    NaN;cfg.benchmark.activeTargets.worstConditionPUFReliability; ...
    cfg.benchmark.activeTargets.sessionPUFReliability; ...
    cfg.puf.maximumReferenceCorrelation;0];
passed = [pufModel.numSelectedEligibleBits >= pufModel.targetBits; ...
    pooledMetrics.reliability >= cfg.benchmark.activeTargets.pufReliability; ...
    pooledMetrics.uniqueness >= uniquenessRange(1) && ...
        pooledMetrics.uniqueness <= uniquenessRange(2); ...
    worstDevelopmentReliability >= ...
        cfg.benchmark.activeTargets.worstConditionPUFReliability; ...
    sessionMetrics.reliability >= ...
        cfg.benchmark.activeTargets.sessionPUFReliability; ...
    pufModel.maximumSelectedCorrelation <= ...
        cfg.puf.maximumReferenceCorrelation;true];
developmentChecks = table(check,current,required,passed, ...
    'VariableNames',{'Check','Current','ReferenceRequirement','Passed'});

study.study = 'TrafoDNA V3.2 projected-PUF development';
study.status = 'exploratory_no_new_final_claim';
study.options = options;
study.pufModel = pufModel;
study.knownTest = knownTestMetrics;
study.unseenDevelopment = unseenMetrics;
study.pooledDevelopment = pooledMetrics;
study.worstDevelopmentReliability = worstDevelopmentReliability;
study.developmentByCondition = conditionTable;
study.sessionDevelopment = sessionMetrics;
study.developmentChecks = developmentChecks;
study.integrity.enrollmentRowsUsed = sum(trainMask);
study.integrity.validationRowsUsed = sum(validationMask);
study.integrity.developmentRowsUsed = sum(developmentMask);
study.integrity.finalRowsUsed = 0;
study.integrity.lockedV3Decision = 'NOT SUPPORTED';
study.integrity.oldFinalScenariosAreObserved = true;

if options.saveResults
    localSaveStudy(study,options);
end
if options.verbose
    localPrintStudy(study);
end
end

function localValidateResults(results)
required = {'cfg','features','metadata','splits','pufIdentityModel'};
for k = 1:numel(required)
    if ~isfield(results,required{k})
        error('TrafoDNA:V32ProjectionMissingField', ...
            'Active results are missing field "%s".',required{k});
    end
end
if ~istable(results.metadata) || ...
        height(results.metadata) ~= size(results.features,1)
    error('TrafoDNA:V32ProjectionInvalidMetadata', ...
        'Active feature rows and metadata must agree.');
end
end

function options = localOptions(options,cfg)
defaults.saveResults = true;
defaults.verbose = true;
defaults.targetBits = cfg.puf.minimumSelectedBits;
defaults.maximumBits = cfg.puf.maximumSelectedBits;
defaults.resultDirectory = fullfile(cfg.projectRoot, ...
    'results_v32_projected');
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(options,names{k})
        options.(names{k}) = defaults.(names{k});
    end
end
options.saveResults = logical(options.saveResults);
options.verbose = logical(options.verbose);
end

function localSaveStudy(study,options)
resultDirectory = options.resultDirectory;
if ~exist(resultDirectory,'dir')
    mkdir(resultDirectory);
end
save(fullfile(resultDirectory,'v32_projected_puf_development.mat'), ...
    'study','-v7.3');
writetable(study.pufModel.selectedBitsTable,fullfile(resultDirectory, ...
    'v32_projected_selected_bits.csv'));
writetable(study.developmentByCondition,fullfile(resultDirectory, ...
    'v32_projected_by_condition.csv'));
writetable(study.developmentChecks,fullfile(resultDirectory, ...
    'v32_projected_development_checks.csv'));
metric = {'GeneratedProjections';'EligibleProjectedCandidates'; ...
    'UniqueEligiblePatterns';'SelectedBits';'TargetBits';'TargetReached'; ...
    'KnownTestReliability';'UnseenDevelopmentReliability'; ...
    'PooledDevelopmentReliability';'PooledDevelopmentUniqueness'; ...
    'WorstDevelopmentReliability';'ThreeSweepReliability'; ...
    'MaximumSelectedCorrelation';'FinalRowsUsed'};
value = [study.pufModel.projectionInfo.totalProjectionCount; ...
    study.pufModel.numEligibleCandidates; ...
    study.pufModel.numUniqueEligiblePatterns; ...
    study.pufModel.numSelectedEligibleBits;study.pufModel.targetBits; ...
    double(study.pufModel.targetReached);study.knownTest.reliability; ...
    study.unseenDevelopment.reliability; ...
    study.pooledDevelopment.reliability; ...
    study.pooledDevelopment.uniqueness; ...
    study.worstDevelopmentReliability; ...
    study.sessionDevelopment.reliability; ...
    study.pufModel.maximumSelectedCorrelation; ...
    study.integrity.finalRowsUsed];
writetable(table(metric,value),fullfile(resultDirectory, ...
    'v32_projected_summary.csv'));
end

function localPrintStudy(study)
fprintf('\n--- TrafoDNA V3.2 Projected-PUF Development ---\n');
fprintf('Generated deterministic projections     : %d\n', ...
    study.pufModel.projectionInfo.totalProjectionCount);
fprintf('Eligible projected candidates            : %d\n', ...
    study.pufModel.numEligibleCandidates);
fprintf('Unique eligible canonical patterns       : %d\n', ...
    study.pufModel.numUniqueEligiblePatterns);
fprintf('Selected mutually admissible bits        : %d\n', ...
    study.pufModel.numSelectedEligibleBits);
fprintf('32-bit development target reached        : %s\n', ...
    localYesNo(study.pufModel.targetReached));
fprintf('Known-test reliability                   : %.4f\n', ...
    study.knownTest.reliability);
fprintf('Unseen-development reliability           : %.4f\n', ...
    study.unseenDevelopment.reliability);
fprintf('Pooled development reliability           : %.4f\n', ...
    study.pooledDevelopment.reliability);
fprintf('Pooled development uniqueness            : %.4f\n', ...
    study.pooledDevelopment.uniqueness);
fprintf('Worst-development-scenario reliability   : %.4f\n', ...
    study.worstDevelopmentReliability);
fprintf('Three-sweep development reliability      : %.4f\n', ...
    study.sessionDevelopment.reliability);
fprintf('Maximum selected-bit correlation         : %.4f\n', ...
    study.pufModel.maximumSelectedCorrelation);
fprintf('Development checks passed                : %d/%d\n', ...
    sum(study.developmentChecks.Passed),height(study.developmentChecks));
fprintf('Locked final rows used                    : %d\n', ...
    study.integrity.finalRowsUsed);
fprintf(['Note: This is exploratory development on already available ' ...
    'non-final rows. It is not a new V3.2 final result.\n']);
end

function text = localYesNo(value)
if value
    text = 'YES';
else
    text = 'NO';
end
end
