function cfg = defaultV32Config()
%DEFAULTV32CONFIG Return the sealed TransformerDNA V3.2 protocol.
%   V3.2 freezes the projected-bit algorithm after the 20-core exploratory
%   result, then tests it on a new 64-core population and new scenarios.
%   Final scenarios 215--218 are defined here but are never generated by
%   MAIN_V32_PREPARE.

cfg = defaultActiveConfig();
cfg.study.name = 'TrafoDNA Projected Challenge-Response V3.2';
cfg.study.protocolVersion = '3.2.0-preregistered';
cfg.study.status = 'preregistered_final_sealed';
cfg.rngSeed = 20260831;

% New population and mechanically generated scenario sequence.
cfg.dataset.numCores = 64;
cfg.dataset.repetitions = 9;
cfg.dataset.trainRepeats = 1:4;
cfg.dataset.validationRepeats = 5:6;
cfg.dataset.testRepeats = 7:9;
cfg.dataset.unseenConditionIds = 209:214;
cfg.dataset.finalHoldoutConditionIds = 215:218;
cfg.dataset.conditions = localBuildV32Scenarios();
cfg.dataset.numConditions = numel(cfg.dataset.conditions);
cfg.dataset.seedByConditionId = true;

% Frozen projection construction selected before any V3.2 final row exists.
cfg.v32.projection.randomProjectionCount = 8192;
cfg.v32.projection.subspaceDimensions = 19;
cfg.v32.projection.withinVarianceRegularization = 0.25;
cfg.v32.projection.energyWeightExponent = 0.50;
cfg.v32.projection.randomSeed = 20260831;
cfg.v32.projection.targetBits = 32;
cfg.v32.projection.maximumBits = 64;

% V3.2 retains the V3 identity and raw-bit thresholds. The old passive-gain
% gate is not reused because the population changes from 20 to 64 cores.
cfg.benchmark.v32Targets.identityAccuracy = 0.60;
cfg.benchmark.v32Targets.maximumEER = 0.20;
cfg.benchmark.v32Targets.pufReliability = 0.90;
cfg.benchmark.v32Targets.pufUniquenessRange = [0.45 0.55];
cfg.benchmark.v32Targets.minimumEligibleBits = 32;
cfg.benchmark.v32Targets.worstConditionPUFReliability = 0.85;
cfg.benchmark.v32Targets.sessionIdentityAccuracy = 0.70;
cfg.benchmark.v32Targets.maximumSessionEER = 0.15;
cfg.benchmark.v32Targets.sessionPUFReliability = 0.93;
cfg.benchmark.v32Targets.maximumReferenceCorrelation = 0.80;

% The one-time final-opening token is intentionally not stored in the
% public source tree. Set TRAFODNA_V32_FINAL_TOKEN locally only when a
% sealed final is authorised for execution.
cfg.v32.finalConfirmationToken = getenv('TRAFODNA_V32_FINAL_TOKEN');
cfg.runtime.resultsDirectory = fullfile(cfg.projectRoot, ...
    'results_v32_preregistered');
cfg.runtime.developmentDirectory = fullfile(cfg.runtime.resultsDirectory, ...
    'development');
cfg.runtime.finalDirectory = fullfile(cfg.runtime.resultsDirectory,'final');
cfg.runtime.figureDirectory = fullfile(cfg.runtime.resultsDirectory,'figures');
cfg.runtime.reportDirectory = fullfile(cfg.runtime.resultsDirectory,'report');
cfg.runtime.preparedBundleFile = fullfile(cfg.runtime.resultsDirectory, ...
    'v32_prepared_bundle.mat');
cfg.runtime.finalResultFile = fullfile(cfg.runtime.finalDirectory, ...
    'v32_final_result.mat');
cfg.runtime.finalLockFile = fullfile(cfg.runtime.finalDirectory, ...
    'V32_FINAL_OPENED.lock');
end

function scenarios = localBuildV32Scenarios()
%LOCALBUILDV32SCENARIOS Use untouched Halton indices 41--58.

haltonIndices = 41:58;
haltonBases = [2 3 5 7 11 13];
unitDesign = zeros(numel(haltonIndices),numel(haltonBases));
for row = 1:size(unitDesign,1)
    for column = 1:size(unitDesign,2)
        unitDesign(row,column) = localRadicalInverse( ...
            haltonIndices(row),haltonBases(column));
    end
end

template = struct('id',0,'temperatureK',293.15,'noiseScale',1, ...
    'sensorGain',1,'resetOffsetAm',0,'stressPa',0,'agingLevel',0, ...
    'healthState','healthy','isUnseen',false,'isFinalHoldout',false);
scenarios = repmat(template,size(unitDesign,1),1);
for k = 1:numel(scenarios)
    scenarios(k).id = 200+k;
    scenarios(k).temperatureK = 283.15+80*unitDesign(k,1);
    scenarios(k).noiseScale = 0.75+1.75*unitDesign(k,2);
    scenarios(k).sensorGain = 0.94+0.12*unitDesign(k,3);
    scenarios(k).resetOffsetAm = -6+12*unitDesign(k,4);
    scenarios(k).stressPa = -4.5e6+9.0e6*unitDesign(k,5);
    scenarios(k).agingLevel = 0.85*unitDesign(k,6);
    scenarios(k).healthState = localHealthState( ...
        scenarios(k).stressPa,scenarios(k).agingLevel);
    scenarios(k).isUnseen = ismember(scenarios(k).id,209:214);
    scenarios(k).isFinalHoldout = ismember(scenarios(k).id,215:218);
end
end

function value = localRadicalInverse(index,base)
value = 0;
fraction = 1/base;
while index > 0
    digit = mod(index,base);
    value = value+digit*fraction;
    index = floor(index/base);
    fraction = fraction/base;
end
end

function state = localHealthState(stressPa,agingLevel)
hasStress = abs(stressPa) >= 1.0e6;
hasAging = agingLevel >= 0.10;
if ~hasStress && ~hasAging
    state = 'healthy';
elseif hasStress && ~hasAging
    state = 'mechanical_stress';
elseif ~hasStress && hasAging
    state = 'thermal_aging';
else
    state = 'combined';
end
end
