function preparedCohort = prepareV33Cohort(cohortCfg)
%PREPAREV33COHORT Fit one frozen V3.3 cohort without final generation.
%   This low-level worker is used by MAIN_V33_PREPARE. It generates only
%   known and unseen-development conditions, then freezes identity and
%   projected-PUF models for the cohort's later final evaluation.

if nargin < 1 || isempty(cohortCfg) || ...
        ~isfield(cohortCfg,'v33') || ...
        ~isfield(cohortCfg.v33,'currentCohort')
    error('TrafoDNA:InvalidV33CohortConfig', ...
        'A materialized V3.3 cohort configuration is required.');
end

developmentCfg = buildV32StageConfig(cohortCfg,'development');
rng(cohortCfg.rngSeed,'twister');
cores = repmat(createActiveCore(1,cohortCfg), ...
    cohortCfg.dataset.numCores,1);
for coreId = 1:cohortCfg.dataset.numCores
    cores(coreId) = createActiveCore(coreId,cohortCfg);
end

dataset = generateActiveDataset(cores,developmentCfg);
localAssertNoFinalRows(dataset,cohortCfg);
splits = splitDataset(dataset.metadata,developmentCfg);
if any(splits.finalHoldout)
    error('TrafoDNA:V33PreparationFinalLeakage', ...
        'Cohort preparation unexpectedly constructed a final partition.');
end

identityModel = tuneIdentityModel(dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train),dataset.metadata(splits.train,:), ...
    dataset.features(splits.validation,:), ...
    dataset.metadata.CoreId(splits.validation), ...
    dataset.metadata(splits.validation,:),cohortCfg);
[knownPrediction,knownIdentity] = localIdentityEvaluation(identityModel, ...
    dataset.features(splits.test,:),dataset.metadata(splits.test,:));
[developmentPrediction,developmentIdentity] = ...
    localIdentityEvaluation(identityModel,dataset.features(splits.unseen,:), ...
    dataset.metadata(splits.unseen,:));

pufIdentityModel = trainActivePUFTransform( ...
    dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train), ...
    dataset.metadata(splits.train,:),cohortCfg);
pufModel = trainV32ProjectedPUF(dataset.features(splits.train,:), ...
    dataset.metadata.CoreId(splits.train),cohortCfg,pufIdentityModel, ...
    dataset.metadata(splits.train,:), ...
    dataset.features(splits.validation,:), ...
    dataset.metadata.CoreId(splits.validation), ...
    dataset.metadata(splits.validation,:),cohortCfg.v32.projection);

pooledMask = splits.test | splits.unseen;
knownPUF = evaluatePUF(pufModel,dataset.features(splits.test,:), ...
    dataset.metadata.CoreId(splits.test),dataset.metadata(splits.test,:));
developmentPUF = evaluatePUF(pufModel, ...
    dataset.features(splits.unseen,:), ...
    dataset.metadata.CoreId(splits.unseen), ...
    dataset.metadata(splits.unseen,:));
pooledPUF = evaluatePUF(pufModel,dataset.features(pooledMask,:), ...
    dataset.metadata.CoreId(pooledMask),dataset.metadata(pooledMask,:));
[worstReliability,pufByCondition] = ...
    computeWorstConditionPUFReliability(pufModel, ...
    dataset.features(pooledMask,:),dataset.metadata.CoreId(pooledMask), ...
    dataset.metadata(pooledMask,:));

readsPerDecision = cohortCfg.session.readsPerDecision;
[~,sessionIdentity] = evaluateIdentitySessions(identityModel, ...
    dataset.features(splits.unseen,:),dataset.metadata(splits.unseen,:), ...
    readsPerDecision);
[sessionPUF,~] = evaluatePUFSessions(pufModel, ...
    dataset.features(pooledMask,:),dataset.metadata(pooledMask,:), ...
    readsPerDecision);
checks = evaluateV32Checks(developmentIdentity,pooledPUF, ...
    worstReliability,sessionIdentity,sessionPUF,pufModel,cohortCfg);

preparedCohort.study = cohortCfg.study.name;
preparedCohort.protocolVersion = cohortCfg.study.protocolVersion;
preparedCohort.status = 'cohort_prepared_final_sealed';
preparedCohort.index = cohortCfg.v33.currentCohort;
preparedCohort.seed = cohortCfg.rngSeed;
preparedCohort.cohortContract = buildV32ProtocolContract(cohortCfg);
preparedCohort.cores = cores;
preparedCohort.featureNames = dataset.featureNames;
preparedCohort.identityModel = identityModel;
preparedCohort.pufIdentityModel = pufIdentityModel;
preparedCohort.pufModel = pufModel;
preparedCohort.development.knownPrediction = knownPrediction;
preparedCohort.development.knownIdentity = knownIdentity;
preparedCohort.development.unseenPrediction = developmentPrediction;
preparedCohort.development.unseenIdentity = developmentIdentity;
preparedCohort.development.knownPUF = knownPUF;
preparedCohort.development.unseenPUF = developmentPUF;
preparedCohort.development.pooledPUF = pooledPUF;
preparedCohort.development.worstConditionPUFReliability = ...
    worstReliability;
preparedCohort.development.pufByCondition = pufByCondition;
preparedCohort.development.sessionIdentity = sessionIdentity;
preparedCohort.development.sessionPUF = sessionPUF;
preparedCohort.development.checks = checks;
preparedCohort.development.readyForFinal = all(checks.Passed);
preparedCohort.integrity.developmentRowsGenerated = ...
    height(dataset.metadata);
preparedCohort.integrity.enrollmentRowsUsed = sum(splits.train);
preparedCohort.integrity.validationRowsUsed = sum(splits.validation);
preparedCohort.integrity.knownTestRowsUsed = sum(splits.test);
preparedCohort.integrity.unseenDevelopmentRowsUsed = sum(splits.unseen);
preparedCohort.integrity.finalRowsGenerated = 0;
preparedCohort.integrity.finalRowsUsed = 0;
preparedCohort.integrity.finalConditionIdsPresent = zeros(1,0);
end

function [prediction,metrics] = localIdentityEvaluation(model,features,metadata)
[prediction,confidence,distances] = predictIdentity(model,features,metadata);
metrics = computeVerificationMetrics(prediction,metadata.CoreId,confidence, ...
    distances,model.coreIds);
end

function localAssertNoFinalRows(dataset,cfg)
if any(dataset.metadata.IsFinalHoldoutCondition) || ...
        any(ismember(dataset.metadata.ConditionId, ...
        cfg.dataset.finalHoldoutConditionIds))
    error('TrafoDNA:V33PreparationFinalLeakage', ...
        'Final rows were generated during V3.3 cohort preparation.');
end
expectedRows = cfg.dataset.numCores* ...
    (cfg.v33.knownScenarioCount+cfg.v33.developmentScenarioCount)* ...
    cfg.dataset.repetitions;
if height(dataset.metadata) ~= expectedRows
    error('TrafoDNA:V33DevelopmentRowCountChanged', ...
        'The cohort development row count differs from the contract.');
end
end
